const ClassesData = [
  // P7
  {
    id: 'C1',
    name: 'P7A',
    level: 'P7',
    subjects: ['ENG', 'MAT', 'SCI', 'SST', 'RE'],
    students: 58,
    male: 29,
    female: 29,
    teachers: [
      { name: 'Paul Ssemwanga', avatar: 'https://i.pravatar.cc/150?img=1' },
      { name: 'Mariam Nabakka', avatar: 'https://i.pravatar.cc/150?img=2' },
      { name: 'Isaac Mugisha', avatar: 'https://i.pravatar.cc/150?img=3' },
      { name: 'Ritah Nanyanzi', avatar: 'https://i.pravatar.cc/150?img=4' },
      { name: 'Josephine Namiiro', avatar: 'https://i.pravatar.cc/150?img=9' },
      { name: 'Tom Lwanga', avatar: 'https://i.pravatar.cc/150?img=10' },
      { name: 'Doreen Mbabazi', avatar: 'https://i.pravatar.cc/150?img=17' },
      { name: 'Ronald Kato', avatar: 'https://i.pravatar.cc/150?img=18' },
    ],
  },
  {
    id: 'C2',
    name: 'P7B',
    level: 'P7',
    subjects: ['ENG', 'MAT', 'SCI', 'SST', 'RE'],
    students: 63,
    male: 31,
    female: 32,
    teachers: [
      { name: 'Isaac Mugisha', avatar: 'https://i.pravatar.cc/150?img=3' },
      { name: 'Ritah Nanyanzi', avatar: 'https://i.pravatar.cc/150?img=4' },
      { name: 'Paul Ssemwanga', avatar: 'https://i.pravatar.cc/150?img=1' },
      { name: 'Mariam Nabakka', avatar: 'https://i.pravatar.cc/150?img=2' },
      { name: 'Josephine Namiiro', avatar: 'https://i.pravatar.cc/150?img=9' },
      { name: 'Tom Lwanga', avatar: 'https://i.pravatar.cc/150?img=10' },
    ],
  },
  {
    id: 'C3',
    name: 'P7C',
    level: 'P7',
    subjects: ['ENG', 'MAT', 'SCI', 'SST', 'RE'],
    students: 60,
    male: 28,
    female: 32,
    teachers: [
      { name: 'David Katongole', avatar: 'https://i.pravatar.cc/150?img=5' },
      { name: 'Annette Kyomuhendo', avatar: 'https://i.pravatar.cc/150?img=6' },
    ],
  },
  {
    id: 'C4',
    name: 'P7D',
    level: 'P7',
    subjects: ['ENG', 'MAT', 'SCI', 'SST', 'RE'],
    students: 62,
    male: 30,
    female: 32,
    teachers: [
      { name: 'Michael Kizito', avatar: 'https://i.pravatar.cc/150?img=7' },
      { name: 'Susan Namatovu', avatar: 'https://i.pravatar.cc/150?img=8' },
    ],
  },

  // P6
  {
    id: 'C5',
    name: 'P6A',
    level: 'P6',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 59,
    male: 27,
    female: 32,
    teachers: [
      { name: 'Josephine Namiiro', avatar: 'https://i.pravatar.cc/150?img=9' },
      { name: 'Tom Lwanga', avatar: 'https://i.pravatar.cc/150?img=10' },
    ],
  },
  {
    id: 'C6',
    name: 'P6B',
    level: 'P6',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 61,
    male: 30,
    female: 31,
    teachers: [
      { name: 'Fred Mutebi', avatar: 'https://i.pravatar.cc/150?img=11' },
      { name: 'Sandra Kaggwa', avatar: 'https://i.pravatar.cc/150?img=12' },
    ],
  },
  {
    id: 'C7',
    name: 'P6C',
    level: 'P6',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 58,
    male: 26,
    female: 32,
    teachers: [
      { name: 'Richard Ssali', avatar: 'https://i.pravatar.cc/150?img=13' },
      { name: 'Mary Nabirye', avatar: 'https://i.pravatar.cc/150?img=14' },
    ],
  },
  {
    id: 'C8',
    name: 'P6D',
    level: 'P6',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 60,
    male: 28,
    female: 32,
    teachers: [
      { name: 'Stella Achieng', avatar: 'https://i.pravatar.cc/150?img=15' },
      { name: 'Brian Okoth', avatar: 'https://i.pravatar.cc/150?img=16' },
    ],
  },

  // P5
  {
    id: 'C9',
    name: 'P5A',
    level: 'P5',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 57,
    male: 27,
    female: 30,
    teachers: [
      { name: 'Doreen Mbabazi', avatar: 'https://i.pravatar.cc/150?img=17' },
      { name: 'Ronald Kato', avatar: 'https://i.pravatar.cc/150?img=18' },
    ],
  },
  {
    id: 'C10',
    name: 'P5B',
    level: 'P5',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 61,
    male: 31,
    female: 30,
    teachers: [
      { name: 'Jackie Namayanja', avatar: 'https://i.pravatar.cc/150?img=19' },
      { name: 'James Mukama', avatar: 'https://i.pravatar.cc/150?img=20' },
    ],
  },
  {
    id: 'C11',
    name: 'P5C',
    level: 'P5',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 58,
    male: 28,
    female: 30,
    teachers: [
      { name: 'Gloria Nankya', avatar: 'https://i.pravatar.cc/150?img=21' },
      { name: 'Elijah Tumusiime', avatar: 'https://i.pravatar.cc/150?img=22' },
    ],
  },
  {
    id: 'C12',
    name: 'P5D',
    level: 'P5',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 60,
    male: 29,
    female: 31,
    teachers: [
      { name: 'Agnes Birungi', avatar: 'https://i.pravatar.cc/150?img=23' },
      { name: 'Simon Obbo', avatar: 'https://i.pravatar.cc/150?img=24' },
    ],
  },

  // P4
  {
    id: 'C13',
    name: 'P4A',
    level: 'P4',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 60,
    male: 30,
    female: 30,
    teachers: [
      { name: 'Daniel Mukasa', avatar: 'https://i.pravatar.cc/150?img=25' },
      { name: 'Sarah Namugga', avatar: 'https://i.pravatar.cc/150?img=26' },
    ],
  },
  {
    id: 'C14',
    name: 'P4B',
    level: 'P4',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 59,
    male: 28,
    female: 31,
    teachers: [
      { name: 'Patrick Owor', avatar: 'https://i.pravatar.cc/150?img=27' },
      { name: 'Rachael Nakato', avatar: 'https://i.pravatar.cc/150?img=28' },
    ],
  },
  {
    id: 'C15',
    name: 'P4C',
    level: 'P4',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 62,
    male: 30,
    female: 32,
    teachers: [
      { name: 'Henry Bukenya', avatar: 'https://i.pravatar.cc/150?img=29' },
      { name: 'Joan Nalwoga', avatar: 'https://i.pravatar.cc/150?img=30' },
    ],
  },
  {
    id: 'C16',
    name: 'P4D',
    level: 'P4',
    subjects: ['ENG', 'MAT', 'SCI', 'SST'],
    students: 60,
    male: 29,
    female: 31,
    teachers: [
      { name: 'Isaac Kabuye', avatar: 'https://i.pravatar.cc/150?img=31' },
      { name: 'Lydia Namirembe', avatar: 'https://i.pravatar.cc/150?img=32' },
    ],
  },

  // P3
  {
    id: 'C17',
    name: 'P3A',
    level: 'P3',
    subjects: ['ENG', 'MAT', 'LIT', 'SST'],
    students: 55,
    male: 26,
    female: 29,
    teachers: [
      { name: 'Eva Musimenta', avatar: 'https://i.pravatar.cc/150?img=33' },
      { name: 'Julius Okello', avatar: 'https://i.pravatar.cc/150?img=34' },
    ],
  },
  {
    id: 'C18',
    name: 'P3B',
    level: 'P3',
    subjects: ['ENG', 'MAT', 'LIT', 'SST'],
    students: 57,
    male: 28,
    female: 29,
    teachers: [
      { name: 'Kenny Sserunkuuma', avatar: 'https://i.pravatar.cc/150?img=35' },
      { name: 'Fiona Akello', avatar: 'https://i.pravatar.cc/150?img=36' },
    ],
  },
  {
    id: 'C19',
    name: 'P3C',
    level: 'P3',
    subjects: ['ENG', 'MAT', 'LIT', 'SST'],
    students: 56,
    male: 27,
    female: 29,
    teachers: [
      { name: 'Charles Nsubuga', avatar: 'https://i.pravatar.cc/150?img=37' },
      { name: 'Diana Ayebale', avatar: 'https://i.pravatar.cc/150?img=38' },
    ],
  },
  {
    id: 'C20',
    name: 'P3D',
    level: 'P3',
    subjects: ['ENG', 'MAT', 'LIT', 'SST'],
    students: 55,
    male: 25,
    female: 30,
    teachers: [
      { name: 'Brian Lubega', avatar: 'https://i.pravatar.cc/150?img=39' },
      { name: 'Milly Atuhaire', avatar: 'https://i.pravatar.cc/150?img=40' },
    ],
  },

  // P2
  {
    id: 'C21',
    name: 'P2A',
    level: 'P2',
    subjects: ['ENG', 'MAT', 'SST', 'ART'],
    students: 52,
    male: 27,
    female: 25,
    teachers: [
      { name: 'Faith Katushabe', avatar: 'https://i.pravatar.cc/150?img=41' },
      { name: 'Peter Ochieng', avatar: 'https://i.pravatar.cc/150?img=42' },
    ],
  },
  {
    id: 'C22',
    name: 'P2B',
    level: 'P2',
    subjects: ['ENG', 'MAT', 'SST', 'ART'],
    students: 50,
    male: 26,
    female: 24,
    teachers: [
      { name: 'Catherine Namanda', avatar: 'https://i.pravatar.cc/150?img=43' },
      { name: 'Martin Ssekito', avatar: 'https://i.pravatar.cc/150?img=44' },
    ],
  },
  {
    id: 'C23',
    name: 'P2C',
    level: 'P2',
    subjects: ['ENG', 'MAT', 'SST', 'ART'],
    students: 53,
    male: 25,
    female: 28,
    teachers: [
      { name: 'Benon Muwanga', avatar: 'https://i.pravatar.cc/150?img=45' },
      { name: 'Naomi Kisakye', avatar: 'https://i.pravatar.cc/150?img=46' },
    ],
  },
  {
    id: 'C24',
    name: 'P2D',
    level: 'P2',
    subjects: ['ENG', 'MAT', 'SST', 'ART'],
    students: 51,
    male: 26,
    female: 25,
    teachers: [
      { name: 'Joan Kembabazi', avatar: 'https://i.pravatar.cc/150?img=47' },
      { name: 'Frank Ntale', avatar: 'https://i.pravatar.cc/150?img=48' },
    ],
  },

  // P1
  {
    id: 'C25',
    name: 'P1A',
    level: 'P1',
    subjects: ['ENG', 'MAT', 'LIT', 'ART'],
    students: 48,
    male: 24,
    female: 24,
    teachers: [
      { name: 'Patience Asiimwe', avatar: 'https://i.pravatar.cc/150?img=49' },
      { name: 'Gerald Nsubuga', avatar: 'https://i.pravatar.cc/150?img=50' },
    ],
  },
  {
    id: 'C26',
    name: 'P1B',
    level: 'P1',
    subjects: ['ENG', 'MAT', 'LIT', 'ART'],
    students: 50,
    male: 25,
    female: 25,
    teachers: [
      { name: 'Dorothy Akena', avatar: 'https://i.pravatar.cc/150?img=51' },
      { name: 'Victor Ouma', avatar: 'https://i.pravatar.cc/150?img=52' },
    ],
  },
  {
    id: 'C27',
    name: 'P1C',
    level: 'P1',
    subjects: ['ENG', 'MAT', 'LIT', 'ART'],
    students: 47,
    male: 23,
    female: 24,
    teachers: [
      { name: 'Beatrice Namusoke', avatar: 'https://i.pravatar.cc/150?img=53' },
      { name: 'Derrick Ssenoga', avatar: 'https://i.pravatar.cc/150?img=54' },
    ],
  },
  {
    id: 'C28',
    name: 'P1D',
    level: 'P1',
    subjects: ['ENG', 'MAT', 'LIT', 'ART'],
    students: 49,
    male: 24,
    female: 25,
    teachers: [
      { name: 'Kevin Tumwine', avatar: 'https://i.pravatar.cc/150?img=55' },
      { name: 'Grace Kobusingye', avatar: 'https://i.pravatar.cc/150?img=56' },
    ],
  },
];

export default ClassesData;
